# Site settings
title: Antonio Tropiano
description: "Personal Page"
url: ""
baseurl: ""
profilepic: "/images/me.png"
bkimage: "/images/bk2.jpg"
google_analytics: UA-75849324-3
font_awesome: "db1d877c5e.js"

author:
  name: "Antonio Tropiano"
  email: antoniotropiano@gmail.com
  twitter_username: tropianhs
  # facebook_username:
  github_username: tropiano
  linkedin_username: tropianhs
  # meetup_name:

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ["README.md", "screenshot-overview.png"]
